name: build

on:
  pull_request: {}
  merge_group:
    branches: [ "main" ]

jobs:

  changed-files:
    name: changed-files
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
      gpu: ${{ steps.changed-files-yaml.outputs.gpu_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            src:
              - '**/*.rs'
              - '**/Cargo.toml'
            gpu:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/*.comp'

  test:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.src == 'true' }}
    name: test-on-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
        with:
          os: ${{ matrix.os }}
          shaderc: false
      - run: |
          cargo build --features "plotters python"
          cargo test --features "plotters python"
        shell: bash

  test-gpu:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.gpu == 'true' }}
    name: test-on-${{ matrix.os }}-with-gpu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
        with:
          os: ${{ matrix.os }}
          shaderc: true
      - run: |
          cargo build --features "plotters python gpu"
          cargo test --features "plotters python gpu"
        shell: bash

  lint:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.src == 'true' }}
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
        with:
          os: ubuntu-latest
          shaderc: true
      - run: |
          cargo clippy --features "plotters python" -- -D warnings
          cargo clippy --features "plotters python gpu" -- -D warnings

  auto-merge:
    needs:
      - test
      - test-gpu
      - lint
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && !failure() && github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr merge --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
