name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: publish-src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
